# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://davidforero.com" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: David Forero # Your name will go here
  description: "A personal portfolio and blog website" # used by search engines

  # Header and footer text
  header_text: >
     <h1>Customer Centric Software Engineer</h1>
     <p>I'm a Software Engineer specialized in Rails, Javascript, and CSS.</p>
  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> and made with love by davefogo.

  # Icons
  rss: false
  email_address: "davefogo@gmail.com"
  behance:
  bitbucket:
  dribbble:
  facebook: "davefogo"
  flickr:
  github: "davefogo"
  google_plus:
  instagram:
  linkedin:  "http://www.linkedin.com/in/luis-david-forero"
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  "http://stackoverflow.com/users/4708669/davefogo"
  steam:
  tumblr:
  twitter:
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-81612704-1"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Read more &raquo;"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Lato:300,400,700,300italic,700italic|Abril+Fatface"

# PAGINATION
paginate: 100
paginate_path: "blog/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

# BUILD SETTINGS
markdown: kramdown

highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed

gems: [jekyll-paginate]
